In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

# Load the dataset

In [ ]:
df = pd.read_csv('/content/patients_500.csv')
df

               name  age  gender  height  weight    bmi      verdict
0     Sharmin Akter   51  female    1.63     100  37.64        Obese
1       Jahid Hasan   32  female    1.65      84  30.85        Obese
2       Karim Ahmed   63    male    1.53      67  28.62   Overweight
3     Farhana Akter   31    male    1.69      90  31.51        Obese
4    Sumaiya Rahman   36    male    1.68      74  26.22   Overweight
..              ...  ...     ...     ...     ...    ...          ...
495  Ayesha Sultana   61    male    1.67      72  25.82   Overweight
496     Habib Uddin   39    male    1.78      57  17.99  Underweight
497   Farhana Akter   25    male    1.68      94  33.30        Obese
498   Sharmin Akter   30  female    1.77     104  33.20        Obese
499    Tanvir Islam   59  female    1.67      69  24.74       Normal

[500 rows x 7 columns]

# EDA

In [ ]:
df.columns

Index(['name', 'age', 'gender', 'height', 'weight', 'bmi', 'verdict'], dtype='object')

## now copy the datasets

In [ ]:
df_copy = df.copy()

## calculate the bmi and add this features.

In [ ]:
# features - 01
df_copy['bmi']= df_copy['weight']/(df_copy['height']/100)**2
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult
...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult

## instead of using directly age we create a new feature called age_group.

In [ ]:
# function to calculate the age avarage
def age_avarage(age):
  if age < 18:
    return 'child'
  elif age >= 18 and age <= 65:
    return 'adult'
  else:
    return 'senior'

In [ ]:
# features - 02
df_copy['age_group'] = df_copy['age'].apply(age_avarage)
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult
...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult

In [ ]:

# features - 03
df_copy["smoking"] = [random.choices(
    ["Non-smoker", "Occasional", "Regular"],
    weights=[0.6, 0.25, 0.15]
)[0] for _ in range(len(df))]

In [ ]:
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Occasional
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker
...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Occasional
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Non-smoker
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker

In [ ]:
#lifecycle risk function.
def lifecycle_risk(row):
    if row['smoking'] == "Regular" and row['bmi'] >= 30:
        return "High Risk"

    elif row['smoking'] == "Occasional" and row['bmi'] >= 25:
        return "Medium Risk"

    else:
        return "Low Risk"

In [ ]:
# features - 04 : lifecycle risk
df_copy['life_cycle']=df_copy.apply(lifecycle_risk,axis=1)
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking,life_cycle
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Occasional,Medium Risk
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker,Low Risk
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker,Low Risk
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker,Low Risk
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker,Low Risk
...,...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker,Low Risk
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker,Low Risk
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Occasional,Medium Risk
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Non-smoker,Low Risk
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker,Low Risk

# Add new features city. and add the random city name.

In [ ]:

cities = [
    "Dhaka", "Chittagong", "Sylhet", "Rajshahi",
    "Khulna", "Barisal", "Rangpur", "Mymensingh",
    "Comilla", "Narayanganj", "Gazipur", "Jessore",
    "Bogura", "Dinajpur", "Noakhali"
]

In [ ]:
# features - 05 : add city in the dataset

In [ ]:
df_copy = df_copy.assign(city=np.random.choice(cities, len(df_copy)))
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking,life_cycle,city
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Regular,Medium Risk,Khulna
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker,Low Risk,Barisal
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker,Low Risk,Barisal
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker,Low Risk,Mymensingh
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker,Low Risk,Rangpur
...,...,...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker,Low Risk,Noakhali
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker,Low Risk,Khulna
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Non-smoker,Medium Risk,Rangpur
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Occasional,Low Risk,Bogura
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker,Low Risk,Jessore

# ekhon amra randomly city er nam use na kore tire create korbo.

In [ ]:
tire1_city = ["Dhaka", "Khulna", "bogura", "Rangpur"]
tier2_city = [
    "Chittagong",
    "Sylhet",
    "Rajshahi",
    "Barisal",
    "Mymensingh",
    "Comilla",
    "Narayanganj",
    "Gazipur",
    "Jessore",
    "Dinajpur",
    "Noakhali",
    "Cox's Bazar",
    "Pabna",
    "Tangail",
    "Feni",
    "Brahmanbaria",
    "Kushtia",
    "Sirajganj",
    "Jamalpur",
    "Satkhira"
]

# write the function for city tier.

In [ ]:
def city_tier(city):
    if city in tire1_city:
        return 1
    elif city in tier2_city:
        return 2
    return 3

# now add the features on the datasets

In [ ]:
df_copy = df_copy.assign(city_tier=df_copy['city'].apply(city_tier))
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking,life_cycle,city,city_tier
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Regular,Medium Risk,Khulna,1
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker,Low Risk,Barisal,2
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker,Low Risk,Barisal,2
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker,Low Risk,Mymensingh,2
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker,Low Risk,Rangpur,1
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker,Low Risk,Noakhali,2
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker,Low Risk,Khulna,1
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Non-smoker,Medium Risk,Rangpur,1
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Occasional,Low Risk,Bogura,3
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker,Low Risk,Jessore,2

In [ ]:
# features - 06: Add income_lpa
incomes = [
    "Below 3 LPA",
    "3-6 LPA",
    "6-10 LPA",
    "10-15 LPA",
    "Above 15 LPA"
]
df_copy["income_lpa"] = np.random.choice(incomes, len(df_copy))



df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking,life_cycle,city,city_tier,income_lpa
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Regular,Medium Risk,Khulna,1,Below 3 LPA
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker,Low Risk,Barisal,2,Above 15 LPA
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker,Low Risk,Barisal,2,3-6 LPA
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker,Low Risk,Mymensingh,2,Below 3 LPA
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker,Low Risk,Rangpur,1,3-6 LPA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker,Low Risk,Noakhali,2,3-6 LPA
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker,Low Risk,Khulna,1,3-6 LPA
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Non-smoker,Medium Risk,Rangpur,1,6-10 LPA
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Occasional,Low Risk,Bogura,3,6-10 LPA
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker,Low Risk,Jessore,2,Below 3 LPA

In [ ]:
# features - 07: Add occupations
occupations = [
    "Student",
    "Employed",
    "Self-Employed",
    "Unemployed",
    "Retired"
]
df_copy["occupations"] = np.random.choice(occupations, len(df_copy))
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking,life_cycle,city,city_tier,income_lpa,occupations
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Regular,Medium Risk,Khulna,1,Below 3 LPA,Self-Employed
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker,Low Risk,Barisal,2,Above 15 LPA,Retired
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker,Low Risk,Barisal,2,3-6 LPA,Self-Employed
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker,Low Risk,Mymensingh,2,Below 3 LPA,Student
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker,Low Risk,Rangpur,1,3-6 LPA,Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker,Low Risk,Noakhali,2,3-6 LPA,Retired
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker,Low Risk,Khulna,1,3-6 LPA,Employed
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Non-smoker,Medium Risk,Rangpur,1,6-10 LPA,Retired
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Occasional,Low Risk,Bogura,3,6-10 LPA,Self-Employed
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker,Low Risk,Jessore,2,Below 3 LPA,Unemployed

In [ ]:
# features - 08: Add insurence_premium_catagory
premium_categories = [
    "Low",
    "Medium",
    "High",
    "Very High"
]
df_copy["insurence_premium_catagory"] = np.random.choice(premium_categories, len(df_copy))
df_copy

,name,age,gender,height,weight,bmi,verdict,age_group,smoking,life_cycle,city,city_tier,income_lpa,occupations,insurence_premium_catagory
0,Sharmin Akter,51,female,1.63,100,376378.486206,Obese,adult,Regular,Medium Risk,Khulna,1,Below 3 LPA,Self-Employed,Medium
1,Jahid Hasan,32,female,1.65,84,308539.944904,Obese,adult,Non-smoker,Low Risk,Barisal,2,Above 15 LPA,Retired,Very High
2,Karim Ahmed,63,male,1.53,67,286214.703746,Overweight,adult,Non-smoker,Low Risk,Barisal,2,3-6 LPA,Self-Employed,High
3,Farhana Akter,31,male,1.69,90,315115.016981,Obese,adult,Non-smoker,Low Risk,Mymensingh,2,Below 3 LPA,Student,High
4,Sumaiya Rahman,36,male,1.68,74,262188.208617,Overweight,adult,Non-smoker,Low Risk,Rangpur,1,3-6 LPA,Employed,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Ayesha Sultana,61,male,1.67,72,258166.302126,Overweight,adult,Non-smoker,Low Risk,Noakhali,2,3-6 LPA,Retired,Medium
496,Habib Uddin,39,male,1.78,57,179901.527585,Underweight,adult,Non-smoker,Low Risk,Khulna,1,3-6 LPA,Employed,Medium
497,Farhana Akter,25,male,1.68,94,333049.886621,Obese,adult,Non-smoker,Medium Risk,Rangpur,1,6-10 LPA,Retired,Medium
498,Sharmin Akter,30,female,1.77,104,331960.803090,Obese,adult,Occasional,Low Risk,Bogura,3,6-10 LPA,Self-Employed,Low
499,Tanvir Islam,59,female,1.67,69,247409.372871,Normal,adult,Non-smoker,Low Risk,Jessore,2,Below 3 LPA,Unemployed,High

# Now we target our features to tain and the further work.

In [ ]:
X = df_copy[['bmi', 'age_group', 'life_cycle', 'city_tier', 'occupations', 'income_lpa']]
Y = df_copy['insurence_premium_catagory']

In [ ]:
X

,bmi,age_group,life_cycle,city_tier,occupations,income_lpa
0,376378.486206,adult,Medium Risk,1,Self-Employed,Below 3 LPA
1,308539.944904,adult,Low Risk,2,Retired,Above 15 LPA
2,286214.703746,adult,Low Risk,2,Self-Employed,3-6 LPA
3,315115.016981,adult,Low Risk,2,Student,Below 3 LPA
4,262188.208617,adult,Low Risk,1,Employed,3-6 LPA
...,...,...,...,...,...,...
495,258166.302126,adult,Low Risk,2,Retired,3-6 LPA
496,179901.527585,adult,Low Risk,1,Employed,3-6 LPA
497,333049.886621,adult,Medium Risk,1,Retired,6-10 LPA
498,331960.803090,adult,Low Risk,3,Self-Employed,6-10 LPA
499,247409.372871,adult,Low Risk,2,Unemployed,Below 3 LPA

In [ ]:
df_copy['occupations'].unique()

array(['Self-Employed', 'Retired', 'Student', 'Employed', 'Unemployed'],
      dtype=object)

In [ ]:
Y

0         Medium
1      Very High
2           High
3           High
4            Low
         ...
495       Medium
496       Medium
497       Medium
498          Low
499         High
Name: insurence_premium_catagory, Length: 500, dtype: object

## catagorical and numaric features.

In [ ]:
catagorical_features = ['age_group', 'life_cycle', 'city_tier', 'occupations', 'income_lpa']
numarical_features = ['bmi']

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [ ]:
preprocessor = ColumnTransformer(
    transformers = [
        ("categorical", OneHotEncoder(sparse_output=False), catagorical_features),
        ("numerical", StandardScaler(), numarical_features)
    ]
)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [ ]:
pipelines = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier())
])

In [ ]:
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
# Fit the pipeline
pipelines.fit(X_train, Y_train)

print("Pipeline created and fitted successfully!")

Pipeline created and fitted successfully!

In [ ]:
accuracy = pipelines.score(X_test, Y_test)
print(f'Test Accuracy: {accuracy:.2%}')

Test Accuracy: 23.00%

In [ ]:
# Evaluate the model
accuracy = pipelines.score(X_test, Y_test)
print(f"Model Accuracy: {accuracy:.2%}")

Model Accuracy: 23.00%

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'classifier__n_estimators': [100, 200, 300],
    'classifier__max_depth': [None, 10, 20],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__criterion': ['gini', 'entropy']
}

# Initialize GridSearchCV
grid_search = GridSearchCV(pipelines, param_grid, cv=5, n_jobs=-1, verbose=1)

# Fit the grid search
grid_search.fit(X_train, Y_train)

# Best parameters and score
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best Cross-validation Accuracy: {grid_search.best_score_:.2%}")

# Evaluate the best model on test set
best_accuracy = grid_search.score(X_test, Y_test)
print(f"Tuned Model Test Accuracy: {best_accuracy:.2%}")

Fitting 5 folds for each of 54 candidates, totalling 270 fits
Best parameters: {'classifier__criterion': 'gini', 'classifier__max_depth': 20, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 200}
Best Cross-validation Accuracy: 26.00%
Tuned Model Test Accuracy: 22.00%

In [ ]:
# now we download the model

import pickle

In [ ]:
pickel_model_path = "model.pkl"
with open(pickel_model_path, 'wb') as file:
    pickle.dump(pipelines, file)